### ISSUE TITLE
Make responsive

### ISSUE THREAD

**Issue by ItzNesbroDev** [ItzNesbroDev/Tods#2]
## make website fits to small devices

**Comment by BinniesLite** [comment]
Hi @ItzNesbroDev, I would love to help with this.

**Comment by abitsalihu** [comment]
Hey guys, I would also like to help if stuck or have another task. :)

**Comment by ItzNesbroDev** [comment]
@BinniesLite Yup, It's Yours

**Comment by BinniesLite** [comment]
Thanks, I'll get it done in the Hacktoberfest
